# action.yml
name: "@gooseus/protolint"
description: "Enforce Protobuf style with protolint"
inputs:
  configDirectory:
    description: "Path to .protolint.yaml"
    required: true
  srcDirectory:
    description: "Path to .proto files"
    required: false
    default: .
  protolintVersion:
    description: "Version of protolint"
    required: false
    default: "0.54.1"

runs:
  using: "composite"
  steps:
    - name: Download protolint
      run: |
        curl -sSL \
          -o /tmp/protolint.tar.gz \
          https://github.com/yoheimuta/protolint/releases/download/v${{ inputs.protolintVersion }}/protolint_${{ inputs.protolintVersion }}_linux_amd64.tar.gz
        tar xzf /tmp/protolint.tar.gz -C /tmp
        chmod +x /tmp/protolint
    - name: Lint
      run: |
        /tmp/protolint lint \
          --config_dir_path "${{ inputs.configDirectory }}" \
          "${{ inputs.srcDirectory }}"