name: "Protolint"
description: "A tool to enforce Protocol Buffer style and conventions"
author: "Plex Systems"

branding:
  icon: "code"
  color: "black"

inputs:
  configDirectory:
    description: "the path to where the .protolint.yaml configuration exists"
    required: true
  srcDirectory:
    description: "the path to where the .proto files are"
    required: false
    default: .
  protolintVersion:
    description: "the version of protolint to use"
    required: false
    default: "0.54.1"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - protolint
    - lint
    - -config_dir_path
    - ${{ inputs.configDirectory }}
    - ${{ inputs.srcDirectory }}
  env:
    PROTOLINT_VERSION: ${{ inputs.protolintVersion }}
